/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RwElevatedButton {
        "custom": boolean;
        "text": string;
        "type": string;
    }
    interface RwFlatButton {
        "custom": boolean;
        "text": string;
        "type": string;
    }
    interface RwOutlinedButton {
        "custom": boolean;
        "text": string;
        "type": string;
    }
}
declare global {
    interface HTMLRwElevatedButtonElement extends Components.RwElevatedButton, HTMLStencilElement {
    }
    var HTMLRwElevatedButtonElement: {
        prototype: HTMLRwElevatedButtonElement;
        new (): HTMLRwElevatedButtonElement;
    };
    interface HTMLRwFlatButtonElement extends Components.RwFlatButton, HTMLStencilElement {
    }
    var HTMLRwFlatButtonElement: {
        prototype: HTMLRwFlatButtonElement;
        new (): HTMLRwFlatButtonElement;
    };
    interface HTMLRwOutlinedButtonElement extends Components.RwOutlinedButton, HTMLStencilElement {
    }
    var HTMLRwOutlinedButtonElement: {
        prototype: HTMLRwOutlinedButtonElement;
        new (): HTMLRwOutlinedButtonElement;
    };
    interface HTMLElementTagNameMap {
        "rw-elevated-button": HTMLRwElevatedButtonElement;
        "rw-flat-button": HTMLRwFlatButtonElement;
        "rw-outlined-button": HTMLRwOutlinedButtonElement;
    }
}
declare namespace LocalJSX {
    interface RwElevatedButton {
        "custom"?: boolean;
        "text"?: string;
        "type"?: string;
    }
    interface RwFlatButton {
        "custom"?: boolean;
        "text"?: string;
        "type"?: string;
    }
    interface RwOutlinedButton {
        "custom"?: boolean;
        "text"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "rw-elevated-button": RwElevatedButton;
        "rw-flat-button": RwFlatButton;
        "rw-outlined-button": RwOutlinedButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rw-elevated-button": LocalJSX.RwElevatedButton & JSXBase.HTMLAttributes<HTMLRwElevatedButtonElement>;
            "rw-flat-button": LocalJSX.RwFlatButton & JSXBase.HTMLAttributes<HTMLRwFlatButtonElement>;
            "rw-outlined-button": LocalJSX.RwOutlinedButton & JSXBase.HTMLAttributes<HTMLRwOutlinedButtonElement>;
        }
    }
}
